<?php

namespace Database\Seeders;

use App\Models\Order;
use App\Models\Customer;
use App\Models\User;
use Illuminate\Database\Seeder;

class OrderSeeder extends Seeder
{
    public function run(): void
    {
        $customers = Customer::all();
        $admin = User::where('email', 'admin@sipedis.com')->first();
        \Illuminate\Support\Facades\Auth::login($admin);
        
        $products = \App\Models\Product::all();
        $orderService = app(\App\Services\OrderService::class);

        foreach ($customers as $customer) {
            // Create 1-3 orders per customer
            $count = rand(1, 3);
            
            for ($i = 0; $i < $count; $i++) {
                // Generate 1-4 random items
                $itemsCount = rand(1, 4);
                $items = [];
                $selectedProducts = $products->random($itemsCount);
                
                foreach ($selectedProducts as $product) {
                    $items[] = [
                        'product_id' => $product->id,
                        'quantity' => rand(1, 20),
                        'notes' => rand(0, 1) ? 'Kirim segera' : null,
                    ];
                }

                $data = [
                    'customer_id' => $customer->id,

                    'order_date' => now()->subDays(rand(1, 60)),
                    'items' => $items,
                    'notes' => 'Generated by seeder',
                ];

                // Create order via service
                $order = $orderService->createOrder($data);

            }
        }
    }
}
